requires 'JSON::MaybeXS', '1.004002';
#requires 'Mojolicious', '8.58';
requires 'Mojo::DOM';
requires 'Mojo::Template';
requires 'LWP::UserAgent', '6.47';
requires 'LWP::Protocol::https', '6.09';
requires 'XML::Twig', '3.52';
requires 'DateTime::Format::DateParse', '0.05';
requires 'Date::Manip', '6.82';
requires 'List::SomeUtils', '0.58';
requires 'HTML::Packer', '2.10';
requires 'CSS::Packer', '2.07';
requires 'JavaScript::Packer', '2.06';