[build]
  publish = "public"
  command = "export PERL5LIB=/opt/buildhome/perl5/lib/perl5 && curl -L https://cpanmin.us | perl - App::cpanminus && cpanm Carton && carton install --deployment && carton exec perl Run.pm"
