name: Trigger Netlify Build
on:
  schedule:
    # Run at minute 15 past every hour
    - cron: '15 */1 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f4124469b90397c94d194db