name: Trigger Netlify Build
on:
  schedule:
    # At minute 15 past every 8th hour from 8 through 18
    - cron: '15 8-18/8 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f4124469b90397c94d194db